### ISSUE TITLE
QA continuous integration

### ISSUE THREAD

**Issue by rsanchej** [hres/cfg-task-service#13]
@shussain I am aware of the time it takes to trigger DEV continuous integration once I have committed code to github `cfg-task-service`/`cfg-classification-service`.  About a minute.

I have committed changes to `cfg-task-service-qa`/`cfg-classification-service-qa` but not sure when will this trigger QA continuous integration? an hour after a commit?  Can you please confirm if continuous integration is setup for QA and make sure that the triggering is the same as DEV's?  Just as fast or faster.

Thanks

**Comment by shussain** [comment]
The Jenkins build for cfg-task-service-qa/cfg-classification-service-qa are similar to cfg-task-service/cfg-classification-service

I did confirm they are running. The repo is pulled very 5 minutes or so. If there is a change, it triggers a build. Due to the polling frquency, build time, etc, I would suggest checking 10-15 minutes after you have pushed commits to the github repo

**Comment by shussain** [comment]
Can I go ahead and close this ticket?

**Comment by rsanchej** [comment]
I just confirmed that the change did get through to QA, however, it appears to have taken closer to over an hour.  If you can shorten that interval that would be great, otherwise yes go ahead and close the ticket.  Thanks

**Comment by shussain** [comment]
I could certainly look into it but @ayoung8 would have to create a ticket for that.

For now, closing ticket

**Comment by jmartinJJ** [comment]
@ayoung8 as per @shussain  suggestion could you please open a ticket for Samir to take a closer look into the above issue.

With thanks, Jane
