### ISSUE TITLE
Investigate cfg-task-service on java-dev for timeouts and heap space issues

### ISSUE THREAD

**Issue by shussain** [hres/cfg-task-service#6]
As reported by Raul: 

_cfg-task-service did deploy [on java-dev] and it did work as intended. This morning there are a lot of time outs and java heap space issues. Can you please take a look at this. This is new._

**Comment by shussain** [comment]
Assigning to Anthony since SOP is that he triages all new tickets

**Comment by ayoung8** [comment]
Raul, your app seems to be causing tomcat to run out of memory.
Since this is only recent, it would be reasonable to assume you are doing more memory intensive operation. Or you have a memory leak (which while rarer in Java, does happen). Is it possible to optimize your code or be more efficient in your operation? 

If you need support debugging the code please have Colette or Jane email me.

**Comment by jmartinJJ** [comment]
Hi Anthony,
Happy to look at things from our side.  What would make that possible is to bounce the server and clear everything before we run it again for troubleshooting.  Could that please be done?  If we had sight to Catalina logs it would put us in a better position to successfully troubleshoot .  Many thanks - Jane

**Comment by rsanchej** [comment]
I just ran DEV and QA this morning. They are both working. The timeouts and out-of-memory errors seem to have been resolved on the server-side. Thanks.

**Comment by shussain** [comment]
Great. Thank you
